"""Syllabus models

Revision ID: 724784fc4a1b
Revises: 
Create Date: 2025-11-11 15:37:56.422054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '724784fc4a1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('teacher', sa.String(length=100), nullable=False),
    sa.Column('syllabus_url', sa.String(length=300), nullable=True),
    sa.Column('subject_code', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('credits', sa.String(length=10), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'teacher', name='_name_teacher_uc')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('attendance', sa.String(length=10), nullable=False),
    sa.Column('test', sa.String(length=10), nullable=False),
    sa.Column('report', sa.String(length=10), nullable=False),
    sa.Column('course_format', sa.String(length=20), nullable=True),
    sa.Column('year', sa.String(length=20), nullable=True),
    sa.Column('classroom', sa.String(length=100), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    op.drop_table('user')
    op.drop_table('course')
    # ### end Alembic commands ###
