"""Initial database setup

Revision ID: ae2de1aff413
Revises: 
Create Date: 2025-10-28 19:47:24.037508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae2de1aff413'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('course_format',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('course_format',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
