"""empty message

Revision ID: b42ba0eaef7e
Revises: bf91ada8ac8f
Create Date: 2025-12-16 16:06:42.078531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b42ba0eaef7e'
down_revision = 'bf91ada8ac8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faculty', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('grade', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('grade')
        batch_op.drop_column('department')
        batch_op.drop_column('faculty')

    # ### end Alembic commands ###
