"""Courseモデルにsyllabus_yearカラムを追加

Revision ID: bf91ada8ac8f
Revises: 724784fc4a1b
Create Date: 2025-11-13 17:02:20.700390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf91ada8ac8f'
down_revision = '724784fc4a1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('syllabus_year', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('syllabus_year')

    # ### end Alembic commands ###
